# Stage 1: Build the application
FROM jelastic/maven:3.9.5-openjdk-21 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn package -DskipTests

# Stage 2: Run the application
FROM openjdk:21-slim
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ARG SPRING_R2DBC_URL
ARG SPRING_R2DBC_USERNAME
ARG SPRING_R2DBC_PASSWORD
ARG SPRING_R2DBC_NAME
ARG SPRING_R2DBC_PROPERTIES_SCHEMA
ARG SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
ARG IMAGE_PATH
ARG keycloak_clientId
ARG keycloak_clientSecret
ARG keycloak_base_url
ENV SPRING_R2DBC_URL=$SPRING_R2DBC_URL
ENV SPRING_R2DBC_USERNAME=$SPRING_R2DBC_USERNAME
ENV SPRING_R2DBC_PASSWORD=$SPRING_R2DBC_PASSWORD
ENV SPRING_R2DBC_NAME=$SPRING_R2DBC_NAME
ENV SPRING_R2DBC_PROPERTIES_SCHEMA=$SPRING_R2DBC_PROPERTIES_SCHEMA
ENV SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=$SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
ENV IMAGE_PATH=$IMAGE_PATH
ENV keycloak_clientId=$keycloak_clientId
ENV keycloak_clientSecret=$keycloak_clientSecret
ENV keycloak_base_url=$keycloak_base_url
ENTRYPOINT ["java","-jar","app.jar"]
