name: Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get previous version
        id: prev_version
        run: |
          echo "PREV_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Bump Version
        id: bump
        uses: nnichols/maven-version-bump-action@v5
        with:
          github-token: ${{ secrets.github_token }}

      - name: Build and push Docker image
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} ghcr.io
          docker build -t ghcr.io/locistar/ato-deckbuilder-server:${{ steps.bump.outputs.version }} .
          docker push ghcr.io/locistar/ato-deckbuilder-server:${{ steps.bump.outputs.version }}
        if: env.PREV_VERSION != steps.bump.outputs.version
